replace_names = {
    'Vittoria Accorombona': 'Victoria Accorombona',
    '20.000 Meilen unter dem Meer': 'Zwanzigtausend Meilen unter\'m Meer',
    'Aufzeichnungen aus einem Totenhaus': 'Aufzeichnungen aus einem toten Hause',
    'Der Glöckner von Notre-Dame': 'Notre Dame in Paris',
    'Das Tal der Angst': 'Das Tal des Grauens',
    'Der Bericht des Arthur Gordon Pym': 'Die denkwürdigen Erlebnisse des Artur Gordon Pym',
    'Bel-Ami': 'Bel Ami',
    'Lebens-Ansichten des Katers Murr': 'Lebensansichten des Katers Murr',
    'Der zerbrochne Krug': 'Der zerbrochene Krug',
    'Knallkopf Wilson': 'Querkopf Wilson',
    'Der Moloch (Wassermann)': 'Der Moloch',
    'Eine Evastochter': 'Eine Evatochter',
    'The Merry Men': 'Die tollen Männer',
    'Das falsche Gewicht. Die Geschichte eines Eichmeisters': 'Das falsche Gewicht',
    'Das Rosazimmer': 'Rosazimmer',
    'Die Arbeiter des Meeres': 'Die Meer-Arbeiter',
    'Die Kameliendame': 'Die Dame mit den Kamelien',
    'Die Beichte eines Toren': 'Die Beichte eines Thoren',
    'Der arme Mann im Tockenburg': 'Lebensgeschichte und Natürliche Ebentheuer des Armen Mannes im Tockenburg',
    'La Bohème': 'Die Bohème',
    'Die wunderbare Reise des kleinen Nils Holgersson mit den Wildgänsen': 'Niels Holgersens wunderbare Reise mit den Wildgänsen',
    'Bleak House': 'Bleakhouse',
    'The Unparalleled Adventure of One Hans Pfaall': 'Das unvergleichliche Abenteuer eines gewissen Hans Pfaall',
    'Heinrich Stillings Jünglingsjahre': 'Henrich Stillings Jünglings-Jahre',
    'Der Kuß von Sentze': 'Der Kuss von Sentze',
    'Der brave Soldat Schwejk': 'Die Abenteuer des braven Soldaten Schwejk',
    'Leben und Thaten des berühmten Ritters Schnapphahnski': 'Leben und Taten des berühmten Ritters Schnapphahnski',
    'Der Hund von Baskerville': 'Der Hund der Baskervilles',
    'Die Schuld des Anderen': 'Die Schuld des Andere',
    'Die Reise zum Mittelpunkt der Erde': 'Reise nach dem Mittelpunkt der Erde',
    'Ein Rückblick aus dem Jahre 2000 auf das Jahr 1887': 'Ein Rückblick aus dem Jahre 2000 auf 1887',
    'Der Mord im Tale von Bascombe': 'Der geheimnisvolle Mord im Thale von Boscombe',
    'Vom Kassenknacker und vom Brandstifter': 'Der gestohlene Kaktus und andere Geschichten',
    'Die Prinzessin von Clèves': 'Die Prinzessin von Cleve',
    'Die Abenteuer des Tom Sawyer': 'Tom Sawyers Abenteuer und Streiche',
    'Micah Clarke': 'Micha Clarke',
    'Das Schloss': 'Das Schloß',
    'Ein schlichtes Herz': 'Ein einfältig Herz',
    'Lamiel': 'Amiel',
    'Wolfs. Geschichten um ein Bürgerhaus': 'Wolfs Geschichten um ein Bürgerhaus',
    'Eine Geschichte aus zwei Städten': 'Eine Geschichte von zwei Städten',
    'Isabella von Ägypten, Kaiser Karl des Fünften erste Jugendliebe': 'Isabella von Ägypten',
    'Altershausen (Wilhelm Raabe)': 'Altershausen',
    'Madame Bovary': 'Frau Bovary',
    'Die vier Mondbrüder (in dem Band »Fledermäuse«)': 'Fledermäuse',
    'Die vier Mondbrüder': 'Fledermäuse',
    'Monsieur Nicolas’ Abenteuer im Lande der Liebe': 'Monsieur Nicolas\' Abenteuer im Lande der Liebe',
    'Leben und Ansichten von Tristram Shandy, Gentleman': 'Tristram Shandy',
    'Der Magnetiseur (E. T. A. Hoffmann)': 'Der Magnetiseur',
    'Albrecht Ostermann (Fragment)': '52 Erzählungen',
    'Baumeister Solness': 'Baumeister Solneß',
    'Die Freude am Leben': 'Die Lebensfreude',
    'Seltsame Leiden eines Theater-Direktors': 'Seltsame Leiden eines Theaterdirektors',
    'Der Schatz von Franchard': 'Der Schatz von Franchar',
    'Master Humphreys Wanduhr': 'Master Humphrey\'s Wanduhr',
    'Die Serapionsbrüder': 'Die Serapions-Brüder',
    'Die Bräutigame der Babette Bomber­ling': 'Die Bräutigame der Babette Bomberling',
    'Tom Jones, die Geschichte eines Findelkindes': 'Die Geschichte des Tom Jones'
}
